In [2]:
import torch
import numpy as np

# 텐서 초기화

In [3]:
# 데이터로부터 직접(directly) 생성하기

In [4]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [5]:
# NumPy 배열로부터 생성하기

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
# 무작위(random) 또는 상수(constant) 값을 사용하기:

In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3197, 0.5889, 0.9391],
        [0.4127, 0.4826, 0.0713]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# 다른 텐서에서 생성하기(shape복제) but, value값은 다르게 설정할 수 있다. 영행렬 등 

In [10]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어쓰기
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5951, 0.6294],
        [0.9827, 0.0456]]) 



In [11]:
# 텐서를 numpy 배열로 변환


In [18]:
t = torch.rand(2,5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# data = [[1,2],[3,4]]
#np_array = np.array(data)
# x_np = torch.from_numpy(np_array)

t: tensor([[0.3380, 0.4451, 0.7760, 0.2657, 0.5774],
        [0.9715, 0.4724, 0.5584, 0.3568, 0.6028]])
n: [[0.33803618 0.44505054 0.77598524 0.26565093 0.5773789 ]
 [0.9715352  0.47238654 0.55836785 0.3567986  0.6027822 ]]


# 넘파이 배열 정복하기

ndarray 는 N-dimensional Array의 약자이다.   
이름 그대로 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원한다.   
2차원 배열은 행렬(matrix)이라고 하는데 행렬에서는 가로줄을 행(row)이라고 하고 세로줄을 열(column)이라고 부른다.  

In [23]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])

print(a.ndim) # 텐서에서는 랭크 = 둘이 같다
print(a.shape)

2
(2, 3)


# 배열 슬라이싱

In [24]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
a[0, :]  # 첫번째 행 전체


array([0, 1, 2, 3])

In [26]:
a[:, 1]  # 두번째 열 전체


array([1, 5])

In [27]:
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지


array([5, 6, 7])

In [28]:
a[:2, :2]


array([[0, 1],
       [4, 5]])

## 배열의 크기 변형 = reshape !!!!!아주중요

In [29]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# 사용하는 원소의 갯수가 정해저 있기 때문에 reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있다. -1을 넣으면 해당 숫자는 다를 값에서 계산되어 사용된다.

In [32]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [34]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [35]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [38]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [39]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

## 배열연결

In [40]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [42]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [44]:
# vstack 명령은 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만든다. 
# 연결할 배열은 마찬가지로 하나의 리스트에 담아야 한다

In [45]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

dstack 명령은 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합친다. 가장 안쪽의 원소의 차원이 증가한다.   
즉 가장 내부의 숫자 원소가 배열이 된다. shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가되는 것이다.  
이 예제의 경우에는 shape 변화가 2개의 (3 x 4) -> 1개의 (3 x 4 x 2)가 된다. 

In [49]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.dstack([c1, c2])


array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [52]:
(np.dstack([c1, c2])).shape


(3, 4, 2)